-- Create a Trigger that automatically creates an invoice for an order. 
DELIMITER $$
DROP TRIGGER IF EXISTS create_order_inv_trig$$

CREATE TRIGGER create_order_inv_trig AFTER INSERT ON `ORDER`
FOR EACH ROW
BEGIN
        INSERT INTO INVOICE (ORDER_ID, PAYMENT_TYPE, STATUS, INVOICE_DATE, DISCOUNT, SKONTO, DELETED)
        VALUES (NEW.ORDER_ID, 'CREDITCARD', 'OPEN', CURRENT_TIMESTAMP(), 0.00, 0.00, 0);
        
		-- SET @NEW_INVOICE_ID = LAST_INSERT_ID();
        
        /*
        INSERT INTO INVOICE_POSITION (INVOICE_ID, POSITION_NR, ARTICLE_ID, AMOUNT)
        SELECT @NEW_INVOICE_ID, ROW_NUMBER() OVER (ORDER BY op.POSITION_NR), a.ARTICLE_ID, op.AMOUNT
        FROM ORDER_POSITION op
        JOIN ARTICLE a ON op.ARTICLE_ID = a.ARTICLE_ID
        WHERE op.ORDER_ID = NEW.ORDER_ID;
        */	
END$$
DELIMITER ;