DELIMITER $$
DROP TRIGGER IF EXISTS delete_customer_invoice_trig$$

CREATE TRIGGER delete_customer_invoice_trig BEFORE DELETE on `ORDER`
FOR EACH ROW
BEGIN
	DELETE FROM INVOICE WHERE ORDER_ID = OLD.ORDER_ID;
END $$
DELIMITER ;