call create_calendar(2024);
SELECT * FROM CALENDAR;

SELECT * FROM CUSTOMER;
CALL order_count(2, 5);
SELECT order_count_per_customer(CUSTOMER_ID, 3, 5) AS ORDER_COUNT, FIRSTNAME, LASTNAME FROM CUSTOMER;

SELECT * FROM CALENDAR;
SELECT date_conversion(CURDATE());
SELECT date_conversion(DATEOFDAY) FROM CALENDAR LIMIT 5;