use thisandthat;

DELIMITER $$

DROP PROCEDURE IF EXISTS TEST_create_transactional_order$$

CREATE PROCEDURE `TEST_create_transactional_order`(IN CUST_ID INT, IN ADDR_ID INT)
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
		SELECT "ERROR DETECTED, ROLLING BACK CHANGES...";
		ROLLBACK;
    END;
    
    START TRANSACTION;
		INSERT INTO `ORDER` (CUSTOMER_ID, ADDRESS_ID, ORDER_DATE, STATUS, DELETED) 
		VALUES (CUST_ID, ADDR_ID, CURDATE(), 'SHIPPED', 0); 
    COMMIT;
END$$

DELIMITER ;