use thisandthat;

SET AUTOCOMMIT = 0;

SET SESSION TRANSACTION ISOLATION 
LEVEL SERIALIZABLE;

SELECT @@global.transaction_isolation; -- global
SELECT @@transaction_isolation;        -- session

INSERT INTO ARTICLE (ARTICLE, PRICE, CURRENCY) VALUES ('Pick', 19.85, 'EUR');
INSERT INTO ARTICLE_NM_ARTICLEGROUP VALUES (4, LAST_INSERT_ID());

COMMIT;

DELETE FROM ARTICLE_NM_ARTICLEGROUP WHERE ARTICLE_ID = LAST_INSERT_ID();
DELETE FROM ARTICLE WHERE ARTICLE_ID = LAST_INSERT_ID();
COMMIT;