CALL create_transactional_invoice(9);

-- sa vad daca exista comenzi fara un invoice
SELECT c.FIRSTNAME, c.LASTNAME, O.ORDER_ID, O.CUSTOMER_ID, O.ORDER_DATE
FROM `ORDER` O
JOIN CUSTOMER c ON O.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN INVOICE I ON O.ORDER_ID = I.ORDER_ID
WHERE I.INVOICE_ID IS NULL;

-- sa vad daca comanda e goala, atunci nu am ce tipari in invoice position
SELECT  COUNT(a.ARTICLE_ID) AS ARTICLE_COUNT
FROM `ORDER` o 
JOIN ORDER_POSITION op ON o.ORDER_ID = op.ORDER_ID
JOIN ARTICLE a ON op.ARTICLE_ID = a.ARTICLE_ID
WHERE o.ORDER_ID = 9;

SELECT * FROM `ORDER`;
SELECT * FROM `INVOICE`;
SELECT * FROM `INVOICE_POSITION`;


DELETE FROM INVOICE_POSITION WHERE INVOICE_ID = 17;
DELETE FROM INVOICE WHERE ORDER_ID=9;

SELECT * FROM ARTICLE;
SELECT * FROM ARTICLEGROUP;


