from django.db import models

class Article(models.Model):
  article = models.CharField(max_length=255)
  price = models.DecimalField(max_digits=9, decimal_places=2)
  currency = models.CharField(max_length=3)
  deleted = models.IntegerField(default=0)
  # groups = models.ManyToManyField('ArticleGroup', related_name='articles', through='ArticleGroupJT')
  groups = models.ManyToManyField('ArticleGroup', related_name='articles', blank=True)
  def __str__(self):
    return self.article + ", " + str(self.price) + " " + self.currency


class ArticleGroup(models.Model): # apparently  i dont need to add articles field here, its automatically generated by django
  articlegroup = models.CharField(max_length=255)
  deleted = models.IntegerField(default=0)
  def __str__(self):
    article_count = self.articles.count()
    return f"{self.articlegroup}: {article_count} articles"

# class ArticleGroupJT(models.Model):
#   article = models.ForeignKey(Article, on_delete=models.CASCADE)
#   group = models.ForeignKey(ArticleGroup, on_delete=models.CASCADE)
#   added_on = models.DateTimeField(auto_now_add=True)
  
