# Generated by Django 5.1.3 on 2024-12-10 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=2)),
                ("postal_code", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=255)),
                ("deleted", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=200)),
                ("surname", models.CharField(max_length=200)),
                ("salutation", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50, verbose_name="customer type")),
                ("created", models.DateTimeField(auto_now=True)),
                ("deleted", models.IntegerField(default=0)),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="customer.address",
                    ),
                ),
            ],
        ),
    ]
